### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "",
  "username": "",
  "password": ""
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ex4@ex4.com",
  "password": "ex4"
}

> {%
    client.global.set("authToken", response.body.token);
%}